### ISSUE TITLE
Ajouter une documentation qui aide les contributeurs à comprendre le code et les fonctionnalités

### ISSUE THREAD

**Issue by bzg** [etalab/sill#11]

**Comment by garronej** [comment]
Unse suggéstion de ce qui pourrais être ajouter pour comprendre les différents éléments qui constitue la stack technique de sill-web:  


# ⚙️ sill-web Technical stack

To find your way in Onyxia, the best approach is to start by getting a surface-level understanding of the libraries that are leveraged in the project.



## For working on what the end user 👁

Anything contained in the [src/ui](https://github.com/InseeFrLab/onyxia-web/tree/main/src/ui) directory.

### react-dsfr 

{% embed url="https://github.com/codegouvfr/react-dsfr" %}

The UI toolkit used in the project it's a react toolit for the [DSFR](https://www.systeme-de-design.gouv.fr/).  

#### [MUI](https://mui.com) integration

react-dsfr is fully compatible with [MUI](https://mui.com/material-ui/).

react-dsfr offers [a library of reusable components](https://components.react-dsfr.codegouv.studio/?path=/story/%F0%9F%87%AB%F0%9F%87%B7-introduction--page) but you can also use [MUI](https://mui.com/material-ui/) components in the project, their aspect will automatically be adapted to blend in with the theme. [Read more here](https://react-dsfr.codegouv.studio/mui)  

### tss-react 

{% embed url="https://www.tss-react.dev/" %}

The library we created for styling. It's reused in [Jitsi](https://jitsi.org/), [Apollo](https://github.com/ApolloAuto/apollo) and more.  

Rules of thumbs when it comes to styling:

* Every component should accept[ an optional `className`](https://github.com/InseeFrLab/onyxia-web/blob/f6e2907e43eea825d39f350207705d564360eb23/src/app/components/App/Footer.tsx#L9)prop it should always [overwrite the internal styles](https://github.com/InseeFrLab/onyxia-web/blob/f6e2907e43eea825d39f350207705d564360eb23/src/app/components/App/Footer.tsx#L55).
* A component should not size or position itself. It should always be the responsibility of the parent component to do it. In other words, you should never have `height`, `width`, `top`, `left`, `right`, `bottom` or `margin` in [the root styles](https://github.com/InseeFrLab/onyxia-web/blob/f6e2907e43eea825d39f350207705d564360eb23/src/app/components/App/Footer.tsx#L16-L23) of your components.
* You should never have a color or a dimension. Use [`fr.spacing`](https://react-dsfr.codegouv.studio/css-in-js) , and [`fr.colors`](https://react-dsfr.codegouv.studio/colors).

### Storybook

{% embed url="https://storybook.js.org" %}

It enables us to test the graphical components in isolation.

To launch Storybook locally run the following command:

```bash
yarn storybook
```  


### Keycloakify 

{% embed url="https://github.com/InseeFrLab/keycloakify" %}

It's a build tool that enables to implement the login and register pages that users see when they are redirected to Keycloak for authentication.

If the app is being run on Keycloak the [`kcContext`](https://github.com/InseeFrLab/onyxia/blob/9ced438bf6bad76a85049d52220617070f6daa79/web/src/index.tsx#L3) isn't `undefined` and it means shat we should render the login/register pages.

If you want to test, uncomment [this line](https://github.com/InseeFrLab/onyxia/blob/9ced438bf6bad76a85049d52220617070f6daa79/web/src/keycloak-theme/login/kcContext.ts#L53) and run `yarn start`. You can also test the login pages in a local keycloak container by running `yarn keycloak`. All the instructions will be printed on the console.

The `keycloak-theme.jar` file is automatically [build](https://github.com/InseeFrLab/onyxia/blob/9ced438bf6bad76a85049d52220617070f6daa79/.github/workflows/ci.yml#L90-L93) and [uploaded as a GitHub release asset](https://github.com/InseeFrLab/onyxia/blob/9ced438bf6bad76a85049d52220617070f6daa79/.github/workflows/ci.yml#L113) by the CI.&#x20;

### type-routes

{% embed url="https://github.com/typehero/type-route" %}

The library we use for routing. It's like [react-router](https://reactrouter.com) but type safe.

### i18nifty 

{% embed url="https://www.i18nifty.dev" %}

For internalization and translation.


## For working on 🧠 of the App

Anything contained in the [src/core](https://github.com/InseeFrLab/onyxia/tree/main/src/core) directory.

### clean-architecture 

{% embed url="https://github.com/garronej/clean-architecture" %}

The framework used to implement strict separation of concern betwen the UI and the Core and high modularity of the code. &#x20;

There is [a snake game (the classic nokia game) example](https://github.com/garronej/snake-clean-architecture) for helping you understand the clean architecture framework. &#x20;

<figure><img src="../../.gitbook/assets/image.png" alt="" width="375"><figcaption><p>Snake game for understanding the clean-architecture framwork</p></figcaption></figure>

### oidc-spa 

{% embed url="https://github.com/garronej/oidc-spa" %}

For everything related to user authentication.&#x20;  

## Meta  

General purpose tools and project lifecycle management.  

### tsafe 

{% embed url="https://www.tsafe.dev" %}

We also heavily rely on [tsafe](https://github.com/garronej/tsafe). It's a collection of utilities that help write cleaner TypeScript code. It is crutial to understand at least [`assert`](https://docs.tsafe.dev/assert), [id](https://docs.tsafe.dev/id), [Equals](https://docs.tsafe.dev/equals) and [symToStr](https://docs.tsafe.dev/symtostr) to be able to contribute on the codebase.

### TS-CI 

{% embed url="https://github.com/garronej/ts-ci" %}

We try, whenever we see an opportunity for it, to publish as standalone NPM module chunks of the code we write for Onyxia-web. It help keep the complexity in check. We use TS-CI as a starter for everything we publish on NPM.

### EVT 

{% embed url="https://www.evt.land" %}

EVT is an event management library (like [RxJS ](https://rxjs.dev)is).

A lot of the things we do is powered under the hood by EVT. You don't need to know EVT to work on onyxia-web however, in order to demystify the parts of the codes that involve it, here are the key ideas to take away:

* If we need to perform particular actions when a value gets changed, we use[`StatefullEvt`](https://docs.evt.land/api/statefulevt).
* We use `Ctx`to detaches event handlers when we no longer need them. (See line 108 on [this playground](https://stackblitz.com/edit/evt-playground?embed=1\&file=index.ts\&hideExplorer=1))
* In React, we use the [useEvt](https://docs.evt.land/react-hooks) hook to work with DOM events.

**Comment by bzg** [comment]
Fermé depuis ton https://github.com/codegouvfr/sill-web/issues/109
